/**
 * @author ldy
 */
package com.cmcc.ms.entity.query;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;


/**
 * The Class AdminHistoryDataExample.
 *
 * @author ldy
 */
public class AdminHistoryDataExample {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database table admin_history_data
     * 
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database table admin_history_data
     * 
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database table admin_history_data
     * 
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table admin_history_data
     * 
     * @mbggenerated
     */
    public AdminHistoryDataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table admin_history_data
     *
     * @param orderByClause the new order by clause
     * @mbggenerated 
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table admin_history_data
     *
     * @return the order by clause
     * @mbggenerated 
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table admin_history_data
     *
     * @param distinct the new distinct
     * @mbggenerated 
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table admin_history_data
     *
     * @return true, if is distinct
     * @mbggenerated 
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table admin_history_data
     *
     * @return the ored criteria
     * @mbggenerated 
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table admin_history_data
     *
     * @param criteria the criteria
     * @mbggenerated 
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table admin_history_data
     *
     * @return the criteria
     * @mbggenerated 
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table admin_history_data
     *
     * @return the criteria
     * @mbggenerated 
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table admin_history_data
     *
     * @return the criteria
     * @mbggenerated 
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table admin_history_data
     * 
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to
     * the database table admin_history_data
     * 
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {

        /** The criteria. */
        protected List<Criterion> criteria;

        /**
         * Instantiates a new generated criteria.
         */
        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        /**
         * Checks if is valid.
         *
         * @return true, if is valid
         */
        public boolean isValid() {
            return criteria.size() > 0;
        }

        /**
         * Gets the all criteria.
         *
         * @return the all criteria
         */
        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        /**
         * Gets the criteria.
         *
         * @return the criteria
         */
        public List<Criterion> getCriteria() {
            return criteria;
        }

        /**
         * Adds the criterion.
         *
         * @param condition the condition
         */
        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        /**
         * Adds the criterion.
         *
         * @param condition the condition
         * @param value the value
         * @param property the property
         */
        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        /**
         * Adds the criterion.
         *
         * @param condition the condition
         * @param value1 the value 1
         * @param value2 the value 2
         * @param property the property
         */
        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        /**
         * And id is null.
         *
         * @return the criteria
         */
        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        /**
         * And id is not null.
         *
         * @return the criteria
         */
        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        /**
         * And id equal to.
         *
         * @param value the value
         * @return the criteria
         */
        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        /**
         * And id not equal to.
         *
         * @param value the value
         * @return the criteria
         */
        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        /**
         * And id greater than.
         *
         * @param value the value
         * @return the criteria
         */
        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        /**
         * And id greater than or equal to.
         *
         * @param value the value
         * @return the criteria
         */
        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        /**
         * And id less than.
         *
         * @param value the value
         * @return the criteria
         */
        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        /**
         * And id less than or equal to.
         *
         * @param value the value
         * @return the criteria
         */
        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        /**
         * And id in.
         *
         * @param values the values
         * @return the criteria
         */
        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        /**
         * And id not in.
         *
         * @param values the values
         * @return the criteria
         */
        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        /**
         * And id between.
         *
         * @param value1 the value 1
         * @param value2 the value 2
         * @return the criteria
         */
        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        /**
         * And id not between.
         *
         * @param value1 the value 1
         * @param value2 the value 2
         * @return the criteria
         */
        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        /**
         * And data name is null.
         *
         * @return the criteria
         */
        public Criteria andDataNameIsNull() {
            addCriterion("DATA_NAME is null");
            return (Criteria) this;
        }

        /**
         * And data name is not null.
         *
         * @return the criteria
         */
        public Criteria andDataNameIsNotNull() {
            addCriterion("DATA_NAME is not null");
            return (Criteria) this;
        }

        /**
         * And data name equal to.
         *
         * @param value the value
         * @return the criteria
         */
        public Criteria andDataNameEqualTo(String value) {
            addCriterion("DATA_NAME =", value, "dataName");
            return (Criteria) this;
        }

        /**
         * And data name not equal to.
         *
         * @param value the value
         * @return the criteria
         */
        public Criteria andDataNameNotEqualTo(String value) {
            addCriterion("DATA_NAME <>", value, "dataName");
            return (Criteria) this;
        }

        /**
         * And data name greater than.
         *
         * @param value the value
         * @return the criteria
         */
        public Criteria andDataNameGreaterThan(String value) {
            addCriterion("DATA_NAME >", value, "dataName");
            return (Criteria) this;
        }

        /**
         * And data name greater than or equal to.
         *
         * @param value the value
         * @return the criteria
         */
        public Criteria andDataNameGreaterThanOrEqualTo(String value) {
            addCriterion("DATA_NAME >=", value, "dataName");
            return (Criteria) this;
        }

        /**
         * And data name less than.
         *
         * @param value the value
         * @return the criteria
         */
        public Criteria andDataNameLessThan(String value) {
            addCriterion("DATA_NAME <", value, "dataName");
            return (Criteria) this;
        }

        /**
         * And data name less than or equal to.
         *
         * @param value the value
         * @return the criteria
         */
        public Criteria andDataNameLessThanOrEqualTo(String value) {
            addCriterion("DATA_NAME <=", value, "dataName");
            return (Criteria) this;
        }

        /**
         * And data name like.
         *
         * @param value the value
         * @return the criteria
         */
        public Criteria andDataNameLike(String value) {
            addCriterion("DATA_NAME like", value, "dataName");
            return (Criteria) this;
        }

        /**
         * And data name not like.
         *
         * @param value the value
         * @return the criteria
         */
        public Criteria andDataNameNotLike(String value) {
            addCriterion("DATA_NAME not like", value, "dataName");
            return (Criteria) this;
        }

        /**
         * And data name in.
         *
         * @param values the values
         * @return the criteria
         */
        public Criteria andDataNameIn(List<String> values) {
            addCriterion("DATA_NAME in", values, "dataName");
            return (Criteria) this;
        }

        /**
         * And data name not in.
         *
         * @param values the values
         * @return the criteria
         */
        public Criteria andDataNameNotIn(List<String> values) {
            addCriterion("DATA_NAME not in", values, "dataName");
            return (Criteria) this;
        }

        /**
         * And data name between.
         *
         * @param value1 the value 1
         * @param value2 the value 2
         * @return the criteria
         */
        public Criteria andDataNameBetween(String value1, String value2) {
            addCriterion("DATA_NAME between", value1, value2, "dataName");
            return (Criteria) this;
        }

        /**
         * And data name not between.
         *
         * @param value1 the value 1
         * @param value2 the value 2
         * @return the criteria
         */
        public Criteria andDataNameNotBetween(String value1, String value2) {
            addCriterion("DATA_NAME not between", value1, value2, "dataName");
            return (Criteria) this;
        }

        /**
         * And upadate time is null.
         *
         * @return the criteria
         */
        public Criteria andUpadateTimeIsNull() {
            addCriterion("UPADATE_TIME is null");
            return (Criteria) this;
        }

        /**
         * And upadate time is not null.
         *
         * @return the criteria
         */
        public Criteria andUpadateTimeIsNotNull() {
            addCriterion("UPADATE_TIME is not null");
            return (Criteria) this;
        }

        /**
         * And upadate time equal to.
         *
         * @param value the value
         * @return the criteria
         */
        public Criteria andUpadateTimeEqualTo(Date value) {
            addCriterion("UPADATE_TIME =", value, "upadateTime");
            return (Criteria) this;
        }

        /**
         * And upadate time not equal to.
         *
         * @param value the value
         * @return the criteria
         */
        public Criteria andUpadateTimeNotEqualTo(Date value) {
            addCriterion("UPADATE_TIME <>", value, "upadateTime");
            return (Criteria) this;
        }

        /**
         * And upadate time greater than.
         *
         * @param value the value
         * @return the criteria
         */
        public Criteria andUpadateTimeGreaterThan(Date value) {
            addCriterion("UPADATE_TIME >", value, "upadateTime");
            return (Criteria) this;
        }

        /**
         * And upadate time greater than or equal to.
         *
         * @param value the value
         * @return the criteria
         */
        public Criteria andUpadateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPADATE_TIME >=", value, "upadateTime");
            return (Criteria) this;
        }

        /**
         * And upadate time less than.
         *
         * @param value the value
         * @return the criteria
         */
        public Criteria andUpadateTimeLessThan(Date value) {
            addCriterion("UPADATE_TIME <", value, "upadateTime");
            return (Criteria) this;
        }

        /**
         * And upadate time less than or equal to.
         *
         * @param value the value
         * @return the criteria
         */
        public Criteria andUpadateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPADATE_TIME <=", value, "upadateTime");
            return (Criteria) this;
        }

        /**
         * And upadate time in.
         *
         * @param values the values
         * @return the criteria
         */
        public Criteria andUpadateTimeIn(List<Date> values) {
            addCriterion("UPADATE_TIME in", values, "upadateTime");
            return (Criteria) this;
        }

        /**
         * And upadate time not in.
         *
         * @param values the values
         * @return the criteria
         */
        public Criteria andUpadateTimeNotIn(List<Date> values) {
            addCriterion("UPADATE_TIME not in", values, "upadateTime");
            return (Criteria) this;
        }

        /**
         * And upadate time between.
         *
         * @param value1 the value 1
         * @param value2 the value 2
         * @return the criteria
         */
        public Criteria andUpadateTimeBetween(Date value1, Date value2) {
            addCriterion("UPADATE_TIME between", value1, value2, "upadateTime");
            return (Criteria) this;
        }

        /**
         * And upadate time not between.
         *
         * @param value1 the value 1
         * @param value2 the value 2
         * @return the criteria
         */
        public Criteria andUpadateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPADATE_TIME not between", value1, value2, "upadateTime");
            return (Criteria) this;
        }

        /**
         * And data download is null.
         *
         * @return the criteria
         */
        public Criteria andDataDownloadIsNull() {
            addCriterion("DATA_DOWNLOAD is null");
            return (Criteria) this;
        }

        /**
         * And data download is not null.
         *
         * @return the criteria
         */
        public Criteria andDataDownloadIsNotNull() {
            addCriterion("DATA_DOWNLOAD is not null");
            return (Criteria) this;
        }

        /**
         * And data download equal to.
         *
         * @param value the value
         * @return the criteria
         */
        public Criteria andDataDownloadEqualTo(String value) {
            addCriterion("DATA_DOWNLOAD =", value, "dataDownload");
            return (Criteria) this;
        }

        /**
         * And data download not equal to.
         *
         * @param value the value
         * @return the criteria
         */
        public Criteria andDataDownloadNotEqualTo(String value) {
            addCriterion("DATA_DOWNLOAD <>", value, "dataDownload");
            return (Criteria) this;
        }

        /**
         * And data download greater than.
         *
         * @param value the value
         * @return the criteria
         */
        public Criteria andDataDownloadGreaterThan(String value) {
            addCriterion("DATA_DOWNLOAD >", value, "dataDownload");
            return (Criteria) this;
        }

        /**
         * And data download greater than or equal to.
         *
         * @param value the value
         * @return the criteria
         */
        public Criteria andDataDownloadGreaterThanOrEqualTo(String value) {
            addCriterion("DATA_DOWNLOAD >=", value, "dataDownload");
            return (Criteria) this;
        }

        /**
         * And data download less than.
         *
         * @param value the value
         * @return the criteria
         */
        public Criteria andDataDownloadLessThan(String value) {
            addCriterion("DATA_DOWNLOAD <", value, "dataDownload");
            return (Criteria) this;
        }

        /**
         * And data download less than or equal to.
         *
         * @param value the value
         * @return the criteria
         */
        public Criteria andDataDownloadLessThanOrEqualTo(String value) {
            addCriterion("DATA_DOWNLOAD <=", value, "dataDownload");
            return (Criteria) this;
        }

        /**
         * And data download like.
         *
         * @param value the value
         * @return the criteria
         */
        public Criteria andDataDownloadLike(String value) {
            addCriterion("DATA_DOWNLOAD like", value, "dataDownload");
            return (Criteria) this;
        }

        /**
         * And data download not like.
         *
         * @param value the value
         * @return the criteria
         */
        public Criteria andDataDownloadNotLike(String value) {
            addCriterion("DATA_DOWNLOAD not like", value, "dataDownload");
            return (Criteria) this;
        }

        /**
         * And data download in.
         *
         * @param values the values
         * @return the criteria
         */
        public Criteria andDataDownloadIn(List<String> values) {
            addCriterion("DATA_DOWNLOAD in", values, "dataDownload");
            return (Criteria) this;
        }

        /**
         * And data download not in.
         *
         * @param values the values
         * @return the criteria
         */
        public Criteria andDataDownloadNotIn(List<String> values) {
            addCriterion("DATA_DOWNLOAD not in", values, "dataDownload");
            return (Criteria) this;
        }

        /**
         * And data download between.
         *
         * @param value1 the value 1
         * @param value2 the value 2
         * @return the criteria
         */
        public Criteria andDataDownloadBetween(String value1, String value2) {
            addCriterion("DATA_DOWNLOAD between", value1, value2, "dataDownload");
            return (Criteria) this;
        }

        /**
         * And data download not between.
         *
         * @param value1 the value 1
         * @param value2 the value 2
         * @return the criteria
         */
        public Criteria andDataDownloadNotBetween(String value1, String value2) {
            addCriterion("DATA_DOWNLOAD not between", value1, value2, "dataDownload");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to
     * the database table admin_history_data
     * 
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        /**
         * Instantiates a new criteria.
         */
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to
     * the database table admin_history_data
     * 
     * @mbggenerated
     */
    public static class Criterion {

        /** The condition. */
        private String condition;

        /** The value. */
        private Object value;

        /** The second value. */
        private Object secondValue;

        /** The no value. */
        private boolean noValue;

        /** The single value. */
        private boolean singleValue;

        /** The between value. */
        private boolean betweenValue;

        /** The list value. */
        private boolean listValue;

        /** The type handler. */
        private String typeHandler;

        /**
         * Gets the condition.
         *
         * @return the condition
         */
        public String getCondition() {
            return condition;
        }

        /**
         * Gets the value.
         *
         * @return the value
         */
        public Object getValue() {
            return value;
        }

        /**
         * Gets the second value.
         *
         * @return the second value
         */
        public Object getSecondValue() {
            return secondValue;
        }

        /**
         * Checks if is no value.
         *
         * @return true, if is no value
         */
        public boolean isNoValue() {
            return noValue;
        }

        /**
         * Checks if is single value.
         *
         * @return true, if is single value
         */
        public boolean isSingleValue() {
            return singleValue;
        }

        /**
         * Checks if is between value.
         *
         * @return true, if is between value
         */
        public boolean isBetweenValue() {
            return betweenValue;
        }

        /**
         * Checks if is list value.
         *
         * @return true, if is list value
         */
        public boolean isListValue() {
            return listValue;
        }

        /**
         * Gets the type handler.
         *
         * @return the type handler
         */
        public String getTypeHandler() {
            return typeHandler;
        }

        /**
         * Instantiates a new criterion.
         *
         * @param condition the condition
         */
        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        /**
         * Instantiates a new criterion.
         *
         * @param condition the condition
         * @param value the value
         * @param typeHandler the type handler
         */
        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        /**
         * Instantiates a new criterion.
         *
         * @param condition the condition
         * @param value the value
         */
        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        /**
         * Instantiates a new criterion.
         *
         * @param condition the condition
         * @param value the value
         * @param secondValue the second value
         * @param typeHandler the type handler
         */
        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        /**
         * Instantiates a new criterion.
         *
         * @param condition the condition
         * @param value the value
         * @param secondValue the second value
         */
        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
