/**
 * @author ldy
 */
package com.cmcc.ms.entity.query;

import java.text.SimpleDateFormat;
import java.util.Date;


/**
 * The Class AdminHistoryData.
 *
 * @author ldy
 */
public class AdminHistoryData {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column admin_history_data.ID
     * 
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column admin_history_data.DATA_NAME
     * 
     * @mbggenerated
     */
    private String dataName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column admin_history_data.UPADATE_TIME
     * 
     * @mbggenerated
     */
    private Date upadateTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column admin_history_data.DATA_DOWNLOAD
     * 
     * @mbggenerated
     */
    private String dataDownload;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column admin_history_data.ID
     * 
     * @return the value of admin_history_data.ID
     * 
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column admin_history_data.ID
     * 
     * @return the value of admin_history_data.ID
     * 
     * @mbggenerated
     */
    @SuppressWarnings("unused")
    private String upadateTimeView;

    /**
     * Gets the upadate time view.
     *
     * @return the upadate time view
     */
    public String getUpadateTimeView() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String sutv = sdf.format(this.upadateTime);

        return sutv;
    }

    /**
     * Sets the upadate time view.
     *
     * @param upadateTimeview the new upadate time view
     */
    public void setUpadateTimeView(String upadateTimeview) {
        this.upadateTimeView = upadateTimeview;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column admin_history_data.ID
     * 
     * @param id
     *            the value for admin_history_data.ID
     * 
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column admin_history_data.DATA_NAME
     * 
     * @return the value of admin_history_data.DATA_NAME
     * 
     * @mbggenerated
     */
    public String getDataName() {
        return dataName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column admin_history_data.DATA_NAME
     * 
     * @param dataName
     *            the value for admin_history_data.DATA_NAME
     * 
     * @mbggenerated
     */
    public void setDataName(String dataName) {
        this.dataName = dataName == null ? null : dataName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column admin_history_data.UPADATE_TIME
     * 
     * @return the value of admin_history_data.UPADATE_TIME
     * 
     * @mbggenerated
     */
    public Date getUpadateTime() {
        return upadateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column admin_history_data.UPADATE_TIME
     * 
     * @param upadateTime
     *            the value for admin_history_data.UPADATE_TIME
     * 
     * @mbggenerated
     */
    public void setUpadateTime(Date upadateTime) {
        this.upadateTime = upadateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column admin_history_data.DATA_DOWNLOAD
     * 
     * @return the value of admin_history_data.DATA_DOWNLOAD
     * 
     * @mbggenerated
     */
    public String getDataDownload() {
        return dataDownload;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column admin_history_data.DATA_DOWNLOAD
     * 
     * @param dataDownload
     *            the value for admin_history_data.DATA_DOWNLOAD
     * 
     * @mbggenerated
     */
    public void setDataDownload(String dataDownload) {
        this.dataDownload = dataDownload == null ? null : dataDownload.trim();
    }
}
