/**
 * @author ldy
 */
package com.cmcc.ms.entity.query;

import java.text.SimpleDateFormat;
import java.util.Date;

import com.cmcc.ms.common.utils.StringUtil;


/**
 * The Class CustomQueryInfo.
 *
 * @author ldy
 */
public class CustomQueryInfo {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column custom_query.id
     * 
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column custom_query.query_name
     * 
     * @mbggenerated
     */
    private String queryName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column custom_query.create_time
     * 
     * @mbggenerated
     */

    //
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column custom_query.user_id
     * 
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column custom_query.query_sql
     * 
     * @mbggenerated
     */
    private String querySql;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column custom_query.querySqlShow
     * 
     * @mbggenerated
     */

    @SuppressWarnings("unused")
    private String createTimeView;

    /**
     * Gets the creates the time view.
     *
     * @return the creates the time view
     */
    public String getCreateTimeView() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String sctv = sdf.format(this.createTime);
        return sctv;
    }

    /**
     * Sets the creates the time view.
     *
     * @param createTimeView the new creates the time view
     */
    public void setCreateTimeView(String createTimeView) {
        this.createTimeView = createTimeView;
    }

    /** The query sql show. */
    @SuppressWarnings("unused")
    private String querySqlShow;

    /**
     * Gets the query sql show.
     *
     * @return the query sql show
     */
    public String getQuerySqlShow() {
        return StringUtil.xssCodeShow(querySql);
    }

    /**
     * Sets the query sql show.
     *
     * @param querySqlShow the new query sql show
     */
    public void setQuerySqlShow(String querySqlShow) {
        this.querySqlShow = StringUtil.xssCodeShow(querySql);
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column custom_query.id
     * 
     * @return the value of custom_query.id
     * 
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column custom_query.id
     * 
     * @param id
     *            the value for custom_query.id
     * 
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column custom_query.query_name
     * 
     * @return the value of custom_query.query_name
     * 
     * @mbggenerated
     */
    public String getQueryName() {
        return queryName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column custom_query.query_name
     * 
     * @param queryName
     *            the value for custom_query.query_name
     * 
     * @mbggenerated
     */
    public void setQueryName(String queryName) {
        this.queryName = queryName == null ? null : queryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column custom_query.create_time
     * 
     * @return the value of custom_query.create_time
     * 
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column custom_query.create_time
     * 
     * @param createTime
     *            the value for custom_query.create_time
     * 
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column custom_query.user_id
     * 
     * @return the value of custom_query.user_id
     * 
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column custom_query.user_id
     * 
     * @param userId
     *            the value for custom_query.user_id
     * 
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column custom_query.query_sql
     * 
     * @return the value of custom_query.query_sql
     * 
     * @mbggenerated
     */
    public String getQuerySql() {
        return querySql;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column custom_query.query_sql
     * 
     * @param querySql
     *            the value for custom_query.query_sql
     * 
     * @mbggenerated
     */
    public void setQuerySql(String querySql) {
        this.querySql = querySql == null ? null : querySql.trim();
    }
}
