/**
 * @author ldy
 */
package com.cmcc.ms.entity.usermanage;


/**
 * The Class UsrManageBatchMessageWithBLOBs.
 */
public class UsrManageBatchMessageWithBLOBs extends UsrManageBatchMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_manage_batch_message.RECEIVE_PHONE_NAME_DETAIL
     *
     * @mbggenerated
     */
    private String receivePhoneNameDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_manage_batch_message.RECEIVE_PHONE_DETAIL
     *
     * @mbggenerated
     */
    private String receivePhoneDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_manage_batch_message.MSG_CONTENT
     *
     * @mbggenerated
     */
    private String msgContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_manage_batch_message.RECEIVE_PHONE_NAME_DETAIL
     *
     * @return the value of usr_manage_batch_message.RECEIVE_PHONE_NAME_DETAIL
     *
     * @mbggenerated
     */
    public String getReceivePhoneNameDetail() {
        return receivePhoneNameDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_manage_batch_message.RECEIVE_PHONE_NAME_DETAIL
     *
     * @param receivePhoneNameDetail the value for usr_manage_batch_message.RECEIVE_PHONE_NAME_DETAIL
     *
     * @mbggenerated
     */
    public void setReceivePhoneNameDetail(String receivePhoneNameDetail) {
        this.receivePhoneNameDetail = receivePhoneNameDetail == null ? null
                : receivePhoneNameDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_manage_batch_message.RECEIVE_PHONE_DETAIL
     *
     * @return the value of usr_manage_batch_message.RECEIVE_PHONE_DETAIL
     *
     * @mbggenerated
     */
    public String getReceivePhoneDetail() {
        return receivePhoneDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_manage_batch_message.RECEIVE_PHONE_DETAIL
     *
     * @param receivePhoneDetail the value for usr_manage_batch_message.RECEIVE_PHONE_DETAIL
     *
     * @mbggenerated
     */
    public void setReceivePhoneDetail(String receivePhoneDetail) {
        this.receivePhoneDetail = receivePhoneDetail == null ? null : receivePhoneDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_manage_batch_message.MSG_CONTENT
     *
     * @return the value of usr_manage_batch_message.MSG_CONTENT
     *
     * @mbggenerated
     */
    public String getMsgContent() {
        return msgContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_manage_batch_message.MSG_CONTENT
     *
     * @param msgContent the value for usr_manage_batch_message.MSG_CONTENT
     *
     * @mbggenerated
     */
    public void setMsgContent(String msgContent) {
        this.msgContent = msgContent == null ? null : msgContent.trim();
    }
}
