package com.cmcc.ms.entity.resource;


/**
 * The Class ResourceBean.
 */
public class ResourceBean {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_devices.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_devices.id
     *
     * @return the value of resource_devices.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_devices.id
     *
     * @param id the value for resource_devices.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

}
