package com.cmcc.ms.entity.resource;

import com.cmcc.ms.common.utils.DateUtils;
import com.cmcc.ms.common.utils.StringUtil;
import com.cmcc.ms.common.utils.TimeUtils;


/**
 * The Class ResourcePorts.
 */
public class ResourcePorts extends ResourceBean {
    
    /** The page num. */
    private String pageNum;
    
    /** The page size. */
    private String pageSize;
    
    /** The begin time. */
    private String beginTime;
    
    /** The end time. */
    private String endTime;
    
    /** The devices ip. */
    private String devicesIp;
    
    /** The devices name. */
    private String devicesName;
    
    /** The service. */
    private String service;
    
    /** The ip addr. */
    private String ipAddr;

    /** The total page. */
    private String totalPage;

    /**
     * Gets the total page.
     *
     * @return the total page
     */
    public String getTotalPage() {
        return totalPage;
    }

    /**
     * Sets the total page.
     *
     * @param totalPage the new total page
     */
    public void setTotalPage(String totalPage) {
        this.totalPage = totalPage;
    }

    /**
     * Gets the ip addr.
     *
     * @return the ip addr
     */
    public String getIpAddr() {
        return ipAddr;
    }

    /**
     * Sets the ip addr.
     *
     * @param ipAddr the new ip addr
     */
    public void setIpAddr(String ipAddr) {
        if ("".equals(ipAddr.trim())) {
            this.ipAddr = null;
        } else {
            this.ipAddr = ipAddr;
        }
    }

    /**
     * Gets the service.
     *
     * @return the service
     */
    public String getService() {
        return service;
    }

    /**
     * Sets the service.
     *
     * @param service the new service
     */
    public void setService(String service) {
        if ("全部".equals(service)) {
            this.service1 = null;
        } else {
            this.service1 = new Long(service);
        }
    }

    /**
     * Gets the devices ip.
     *
     * @return the devices ip
     */
    public String getDevicesIp() {
        return devicesIp;
    }

    /**
     * Sets the devices ip.
     *
     * @param devicesIp the new devices ip
     */
    public void setDevicesIp(String devicesIp) {
        this.devicesIp = devicesIp;
    }

    /**
     * Gets the devices name.
     *
     * @return the devices name
     */
    public String getDevicesName() {
        return devicesName;
    }

    /**
     * Sets the devices name.
     *
     * @param devicesName the new devices name
     */
    public void setDevicesName(String devicesName) {
        this.devicesName = devicesName;
    }

    /**
     * Gets the page num.
     *
     * @return the page num
     */
    public String getPageNum() {
        return pageNum;
    }

    /**
     * Sets the page num.
     *
     * @param pageNum the new page num
     */
    public void setPageNum(String pageNum) {
        this.pageNum = pageNum;
    }

    /**
     * Gets the page size.
     *
     * @return the page size
     */
    public String getPageSize() {
        return pageSize;
    }

    /**
     * Sets the page size.
     *
     * @param pageSize the new page size
     */
    public void setPageSize(String pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * Gets the begin time.
     *
     * @return the begin time
     */
    public String getBeginTime() {
        return beginTime;
    }

    /**
     * Sets the begin time.
     *
     * @param beginTime the new begin time
     */
    public void setBeginTime(String beginTime) {
        if (StringUtil.isNotNUll(beginTime)) {
            this.beginTime = DateUtils.getSpecifiedDayBefore(TimeUtils.FORMAT_DATE, beginTime);
        } else {
            this.beginTime = null;
        }
    }

    /**
     * Gets the end time.
     *
     * @return the end time
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * Sets the end time.
     *
     * @param endTime the new end time
     */
    public void setEndTime(String endTime) {
        if (StringUtil.isNotNUll(endTime)) {
            this.endTime = DateUtils.getSpecifiedDayAfter(TimeUtils.FORMAT_DATE, endTime);
        } else {
            this.endTime = null;
        }
    }

    /** The province. */
    private String province;

    /**
     * Gets the province.
     *
     * @return the province
     */
    public String getProvince() {
        return province;
    }

    /**
     * Sets the province.
     *
     * @param province the new province
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_ports.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_ports.deviceid
     *
     * @mbggenerated
     */
    private Long deviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_ports.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_ports.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_ports.service_1
     *
     * @mbggenerated
     */
    private Long service1;

    /** The service 1 view. */
    private String service1View;

    /**
     * Gets the service 1 view.
     *
     * @return the service 1 view
     */
    public String getService1View() {
        return service1View;
    }

    /**
     * Sets the service 1 view.
     *
     * @param service1View the new service 1 view
     */
    public void setService1View(String service1View) {
        this.service1View = service1View;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_ports.service_2
     *
     * @mbggenerated
     */
    private Long service2;

    /** The service 2 view. */
    private String service2View;

    /**
     * Gets the service 2 view.
     *
     * @return the service 2 view
     */
    public String getService2View() {
        return service2View;
    }

    /**
     * Sets the service 2 view.
     *
     * @param service2View the new service 2 view
     */
    public void setService2View(String service2View) {
        this.service2View = service2View;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_ports.service_3
     *
     * @mbggenerated
     */
    private Long service3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_ports.service_jf
     *
     * @mbggenerated
     */
    private Long serviceJf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_ports.peer_device
     *
     * @mbggenerated
     */
    private String peerDevice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_ports.zb_itemid_trafficin
     *
     * @mbggenerated
     */
    private Long zbItemidTrafficin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_ports.zb_itemid_trafficout
     *
     * @mbggenerated
     */
    private Long zbItemidTrafficout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_ports.zb_itemid_utilin
     *
     * @mbggenerated
     */
    private Long zbItemidUtilin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_ports.zb_itemid_utilout
     *
     * @mbggenerated
     */
    private Long zbItemidUtilout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_ports.zb_itemid_bandwidth
     *
     * @mbggenerated
     */
    private Long zbItemidBandwidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_ports.status
     *
     * @mbggenerated
     */
    private Byte status;

    /** The status view. */
    private String statusView;

    /**
     * Gets the status view.
     *
     * @return the status view
     */
    public String getStatusView() {
        return statusView;
    }

    /**
     * Sets the status view.
     *
     * @param statusView the new status view
     */
    public void setStatusView(String statusView) {
        this.statusView = statusView;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_ports.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /** The create time view. */
    private String createTimeView;

    /**
     * Gets the creates the time view.
     *
     * @return the creates the time view
     */
    public String getCreateTimeView() {
        if (createTime != null) {
            createTimeView = DateUtils.dateToStr(createTime, DateUtils.YMD_DASH);
        }
        return createTimeView;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_ports.lastmodified_time
     *
     * @mbggenerated
     */
    private Integer lastmodifiedTime;

    /** The lastmodified time view. */
    private String lastmodifiedTimeView;

    /**
     * Gets the lastmodified time view.
     *
     * @return the lastmodified time view
     */
    public String getLastmodifiedTimeView() {
        if (lastmodifiedTime != null) {
            lastmodifiedTimeView = DateUtils.dateToStr(lastmodifiedTime, DateUtils.YMD_DASH);
        }
        return lastmodifiedTimeView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_ports.id
     *
     * @return the value of resource_ports.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_ports.id
     *
     * @param id the value for resource_ports.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_ports.deviceid
     *
     * @return the value of resource_ports.deviceid
     *
     * @mbggenerated
     */
    public Long getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_ports.deviceid
     *
     * @param deviceid the value for resource_ports.deviceid
     *
     * @mbggenerated
     */
    public void setDeviceid(Long deviceid) {
        this.deviceid = deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_ports.name
     *
     * @return the value of resource_ports.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_ports.name
     *
     * @param name the value for resource_ports.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_ports.type
     *
     * @return the value of resource_ports.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_ports.type
     *
     * @param type the value for resource_ports.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        if ("全部".equals(type)) {
            this.type = null;
        } else {
            this.type = type == null ? null : type.trim();
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_ports.service_1
     *
     * @return the value of resource_ports.service_1
     *
     * @mbggenerated
     */
    public Long getService1() {
        return service1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_ports.service_1
     *
     * @param service1 the value for resource_ports.service_1
     *
     * @mbggenerated
     */
    public void setService1(Long service1) {
        this.service1 = service1;
        this.service = service1 + "";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_ports.service_2
     *
     * @return the value of resource_ports.service_2
     *
     * @mbggenerated
     */
    public Long getService2() {
        return service2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_ports.service_2
     *
     * @param service2 the value for resource_ports.service_2
     *
     * @mbggenerated
     */
    public void setService2(Long service2) {
        this.service2 = service2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_ports.service_3
     *
     * @return the value of resource_ports.service_3
     *
     * @mbggenerated
     */
    public Long getService3() {
        return service3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_ports.service_3
     *
     * @param service3 the value for resource_ports.service_3
     *
     * @mbggenerated
     */
    public void setService3(Long service3) {
        this.service3 = service3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_ports.service_jf
     *
     * @return the value of resource_ports.service_jf
     *
     * @mbggenerated
     */
    public Long getServiceJf() {
        return serviceJf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_ports.service_jf
     *
     * @param serviceJf the value for resource_ports.service_jf
     *
     * @mbggenerated
     */
    public void setServiceJf(Long serviceJf) {
        this.serviceJf = serviceJf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_ports.peer_device
     *
     * @return the value of resource_ports.peer_device
     *
     * @mbggenerated
     */
    public String getPeerDevice() {
        return peerDevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_ports.peer_device
     *
     * @param peerDevice the value for resource_ports.peer_device
     *
     * @mbggenerated
     */
    public void setPeerDevice(String peerDevice) {
        this.peerDevice = peerDevice == null ? null : peerDevice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_ports.zb_itemid_trafficin
     *
     * @return the value of resource_ports.zb_itemid_trafficin
     *
     * @mbggenerated
     */
    public Long getZbItemidTrafficin() {
        return zbItemidTrafficin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_ports.zb_itemid_trafficin
     *
     * @param zbItemidTrafficin the value for resource_ports.zb_itemid_trafficin
     *
     * @mbggenerated
     */
    public void setZbItemidTrafficin(Long zbItemidTrafficin) {
        this.zbItemidTrafficin = zbItemidTrafficin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_ports.zb_itemid_trafficout
     *
     * @return the value of resource_ports.zb_itemid_trafficout
     *
     * @mbggenerated
     */
    public Long getZbItemidTrafficout() {
        return zbItemidTrafficout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_ports.zb_itemid_trafficout
     *
     * @param zbItemidTrafficout the value for resource_ports.zb_itemid_trafficout
     *
     * @mbggenerated
     */
    public void setZbItemidTrafficout(Long zbItemidTrafficout) {
        this.zbItemidTrafficout = zbItemidTrafficout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_ports.zb_itemid_utilin
     *
     * @return the value of resource_ports.zb_itemid_utilin
     *
     * @mbggenerated
     */
    public Long getZbItemidUtilin() {
        return zbItemidUtilin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_ports.zb_itemid_utilin
     *
     * @param zbItemidUtilin the value for resource_ports.zb_itemid_utilin
     *
     * @mbggenerated
     */
    public void setZbItemidUtilin(Long zbItemidUtilin) {
        this.zbItemidUtilin = zbItemidUtilin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_ports.zb_itemid_utilout
     *
     * @return the value of resource_ports.zb_itemid_utilout
     *
     * @mbggenerated
     */
    public Long getZbItemidUtilout() {
        return zbItemidUtilout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_ports.zb_itemid_utilout
     *
     * @param zbItemidUtilout the value for resource_ports.zb_itemid_utilout
     *
     * @mbggenerated
     */
    public void setZbItemidUtilout(Long zbItemidUtilout) {
        this.zbItemidUtilout = zbItemidUtilout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_ports.zb_itemid_bandwidth
     *
     * @return the value of resource_ports.zb_itemid_bandwidth
     *
     * @mbggenerated
     */
    public Long getZbItemidBandwidth() {
        return zbItemidBandwidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_ports.zb_itemid_bandwidth
     *
     * @param zbItemidBandwidth the value for resource_ports.zb_itemid_bandwidth
     *
     * @mbggenerated
     */
    public void setZbItemidBandwidth(Long zbItemidBandwidth) {
        this.zbItemidBandwidth = zbItemidBandwidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_ports.status
     *
     * @return the value of resource_ports.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_ports.status
     *
     * @param status the value for resource_ports.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_ports.create_time
     *
     * @return the value of resource_ports.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_ports.create_time
     *
     * @param createTime the value for resource_ports.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_ports.lastmodified_time
     *
     * @return the value of resource_ports.lastmodified_time
     *
     * @mbggenerated
     */
    public Integer getLastmodifiedTime() {
        return lastmodifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_ports.lastmodified_time
     *
     * @param lastmodifiedTime the value for resource_ports.lastmodified_time
     *
     * @mbggenerated
     */
    public void setLastmodifiedTime(Integer lastmodifiedTime) {
        this.lastmodifiedTime = lastmodifiedTime;
    }
}
