INSERT INTO `cdnms`.`sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`) VALUES ('155', '数据管理', '0', '1', 'dataManage', '3'); 
INSERT INTO `cdnms`.`sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`) VALUES ('156', '本省率分析', '155', '2', 'proAnalysis', '3'); 

INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('157','全国','0','1',NULL,'-600','全国','1');
INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('158','国际公司','157','2','','-6','国际','2');
INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('159','上海移动','157','2',NULL,'-6','上海','3');
INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('160','云南移动','157','2',NULL,'-6','云南','3');
INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('161','内蒙古移动','157','2',NULL,'-6','内蒙古','3');
INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('162','北京移动','157','2',NULL,'-6','北京','3');
INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('163','吉林移动','157','2',NULL,'-6','吉林','3');
INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('164','四川移动','157','2',NULL,'-6','四川','3');
INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('165','天津移动','157','2',NULL,'-6','天津','3');
INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('166','宁夏移动','157','2',NULL,'-6','宁夏','3');
INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('167','安徽移动','157','2',NULL,'-6','安徽','3');
INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('168','山东移动','157','2',NULL,'-6','山东','3');
INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('169','山西移动','157','2',NULL,'-6','山西','3');
INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('170','广东移动','157','2',NULL,'-6','广东','3');
INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('171','广西移动','157','2',NULL,'-6','广西','3');
INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('172','新疆移动','157','2',NULL,'-6','新疆','3');
INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('173','江苏移动','157','2',NULL,'-6','江苏','3');
INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('174','江西移动','157','2',NULL,'-6','江西','3');
INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('175','河北移动','157','2',NULL,'-6','河北','3');
INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('176','河南移动','157','2',NULL,'-6','河南','3');
INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('177','浙江移动','157','2',NULL,'-6','浙江','3');
INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('178','海南移动','157','2',NULL,'-6','海南','3');
INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('179','湖北移动','157','2',NULL,'-6','湖北','3');
INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('180','湖南移动','157','2',NULL,'-6','湖南','3');
INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('181','甘肃移动','157','2',NULL,'-6','甘肃','3');
INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('182','福建移动','157','2',NULL,'-6','福建','3');
INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('183','西藏移动','157','2',NULL,'-6','西藏','3');
INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('184','贵州移动','157','2',NULL,'-6','贵州','3');
INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('185','辽宁移动','157','2',NULL,'-6','辽宁','3');
INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('186','重庆移动','157','2',NULL,'-6','重庆','3');
INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('187','陕西移动','157','2',NULL,'-6','陕西','3');
INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('188','青海移动','157','2',NULL,'-6','青海','3');
INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('189','黑龙江移动','157','2',NULL,'-6','黑龙江','3');
INSERT INTO `sys_menus` (`MENU_ID`, `MENU_NAME`, `PARENT_ID`, `DEPTH`, `URL`, `TYPE`, `IMG`, `SORT`) VALUES('190','香港移动','157','2',NULL,'-6','香港','3');