/**
 * @author ldy
 */
package com.cmcc.ms.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.cmcc.ms.entity.query.CustomQueryInfo;
import com.cmcc.ms.entity.query.CustomQueryInfoExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;


/**
 * The Interface CustomQueryInfoMapper.
 *
 * @author ldy
 */
public interface CustomQueryInfoMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table custom_query
     *
     * @param example the example
     * @return the int
     * @mbggenerated 
     */
    int countByExample(CustomQueryInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table custom_query
     *
     * @param example the example
     * @return the int
     * @mbggenerated 
     */
    int deleteByExample(CustomQueryInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table custom_query
     *
     * @param id the id
     * @return the int
     * @mbggenerated 
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table custom_query
     *
     * @param record the record
     * @return the int
     * @mbggenerated 
     */
    int insert(CustomQueryInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table custom_query
     *
     * @param record the record
     * @return the int
     * @mbggenerated 
     */
    int insertSelective(CustomQueryInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table custom_query
     *
     * @param example the example
     * @return the list
     * @mbggenerated 
     */
    List<CustomQueryInfo> selectByExampleWithBLOBs(CustomQueryInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table custom_query
     *
     * @param example the example
     * @return the list
     * @mbggenerated 
     */
    List<CustomQueryInfo> selectByExample(CustomQueryInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table custom_query
     *
     * @param id the id
     * @return the custom query info
     * @mbggenerated 
     */
    CustomQueryInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table custom_query
     *
     * @param record the record
     * @param example the example
     * @return the int
     * @mbggenerated 
     */
    int updateByExampleSelective(@Param("record") CustomQueryInfo record,
                                 @Param("example") CustomQueryInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table custom_query
     *
     * @param record the record
     * @param example the example
     * @return the int
     * @mbggenerated 
     */
    int updateByExampleWithBLOBs(@Param("record") CustomQueryInfo record,
                                 @Param("example") CustomQueryInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table custom_query
     *
     * @param record the record
     * @param example the example
     * @return the int
     * @mbggenerated 
     */
    int updateByExample(@Param("record") CustomQueryInfo record,
                        @Param("example") CustomQueryInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table custom_query
     *
     * @param record the record
     * @return the int
     * @mbggenerated 
     */
    int updateByPrimaryKeySelective(CustomQueryInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table custom_query
     *
     * @param record the record
     * @return the int
     * @mbggenerated 
     */
    int updateByPrimaryKeyWithBLOBs(CustomQueryInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table custom_query
     *
     * @param record the record
     * @return the int
     * @mbggenerated 
     */
    int updateByPrimaryKey(CustomQueryInfo record);

    /**
     * 自定义查询.
     *
     * @param pb the pb
     * @return the list
     */
    List<CustomQueryInfo> selectForCustomQueryShow(PageBounds pb);

    /**
     * Gets the custom query size.
     *
     * @author ldy
     * @return the custom query size
     */
    int getCustomQuerySize();

}
