/**
 * @author ldy
 */
package com.cmcc.ms.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.cmcc.ms.entity.system.SysMenus;
import com.cmcc.ms.entity.system.SysMenusExample;


/**
 * The Interface SysMenusMapper.
 *
 * @author ldy
 */
public interface SysMenusMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_menus
     *
     * @param example the example
     * @return the int
     * @mbggenerated 
     */
    int countByExample(SysMenusExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_menus
     *
     * @param example the example
     * @return the int
     * @mbggenerated 
     */
    int deleteByExample(SysMenusExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_menus
     *
     * @param menuId the menu id
     * @return the int
     * @mbggenerated 
     */
    int deleteByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_menus
     *
     * @param record the record
     * @return the int
     * @mbggenerated 
     */
    int insert(SysMenus record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_menus
     *
     * @param record the record
     * @return the int
     * @mbggenerated 
     */
    int insertSelective(SysMenus record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_menus
     *
     * @param example the example
     * @return the list
     * @mbggenerated 
     */
    List<SysMenus> selectByExample(SysMenusExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_menus
     *
     * @param menuId the menu id
     * @return the sys menus
     * @mbggenerated 
     */
    SysMenus selectByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_menus
     *
     * @param record the record
     * @param example the example
     * @return the int
     * @mbggenerated 
     */
    int updateByExampleSelective(@Param("record") SysMenus record,
                                 @Param("example") SysMenusExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_menus
     *
     * @param record the record
     * @param example the example
     * @return the int
     * @mbggenerated 
     */
    int updateByExample(@Param("record") SysMenus record, @Param("example") SysMenusExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_menus
     *
     * @param record the record
     * @return the int
     * @mbggenerated 
     */
    int updateByPrimaryKeySelective(SysMenus record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_menus
     *
     * @param record the record
     * @return the int
     * @mbggenerated 
     */
    int updateByPrimaryKey(SysMenus record);
}
