/**
 * @author ldy
 */
package com.cmcc.ms.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.cmcc.ms.entity.system.SysRoles;
import com.cmcc.ms.entity.system.SysRolesExample;


/**
 * The Interface SysRolesMapper.
 *
 * @author ldy
 */
public interface SysRolesMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_roles
     *
     * @param example the example
     * @return the int
     * @mbggenerated 
     */
    int countByExample(SysRolesExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_roles
     *
     * @param example the example
     * @return the int
     * @mbggenerated 
     */
    int deleteByExample(SysRolesExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_roles
     *
     * @param roleId the role id
     * @return the int
     * @mbggenerated 
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_roles
     *
     * @param record the record
     * @return the int
     * @mbggenerated 
     */
    int insert(SysRoles record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_roles
     *
     * @param record the record
     * @return the int
     * @mbggenerated 
     */
    int insertSelective(SysRoles record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_roles
     *
     * @param example the example
     * @return the list
     * @mbggenerated 
     */
    List<SysRoles> selectByExample(SysRolesExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_roles
     *
     * @param roleId the role id
     * @return the sys roles
     * @mbggenerated 
     */
    SysRoles selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_roles
     *
     * @param record the record
     * @param example the example
     * @return the int
     * @mbggenerated 
     */
    int updateByExampleSelective(@Param("record") SysRoles record,
                                 @Param("example") SysRolesExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_roles
     *
     * @param record the record
     * @param example the example
     * @return the int
     * @mbggenerated 
     */
    int updateByExample(@Param("record") SysRoles record, @Param("example") SysRolesExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_roles
     *
     * @param record the record
     * @return the int
     * @mbggenerated 
     */
    int updateByPrimaryKeySelective(SysRoles record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_roles
     *
     * @param record the record
     * @return the int
     * @mbggenerated 
     */
    int updateByPrimaryKey(SysRoles record);
}
