/**
 * @author ldy
 */
package com.cmcc.ms.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.cmcc.ms.entity.system.SysUsers;
import com.cmcc.ms.entity.system.SysUsersExample;


/**
 * The Interface SysUsersMapper.
 *
 * @author ldy
 */
public interface SysUsersMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_users
     *
     * @param example the example
     * @return the int
     * @mbggenerated 
     */
    int countByExample(SysUsersExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_users
     *
     * @param example the example
     * @return the int
     * @mbggenerated 
     */
    int deleteByExample(SysUsersExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_users
     *
     * @param userId the user id
     * @return the int
     * @mbggenerated 
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_users
     *
     * @param record the record
     * @return the int
     * @mbggenerated 
     */
    int insert(SysUsers record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_users
     *
     * @param record the record
     * @return the int
     * @mbggenerated 
     */
    int insertSelective(SysUsers record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_users
     *
     * @param example the example
     * @return the list
     * @mbggenerated 
     */
    List<SysUsers> selectByExample(SysUsersExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_users
     *
     * @param userId the user id
     * @return the sys users
     * @mbggenerated 
     */
    SysUsers selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_users
     *
     * @param record the record
     * @param example the example
     * @return the int
     * @mbggenerated 
     */
    int updateByExampleSelective(@Param("record") SysUsers record,
                                 @Param("example") SysUsersExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_users
     *
     * @param record the record
     * @param example the example
     * @return the int
     * @mbggenerated 
     */
    int updateByExample(@Param("record") SysUsers record, @Param("example") SysUsersExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_users
     *
     * @param record the record
     * @return the int
     * @mbggenerated 
     */
    int updateByPrimaryKeySelective(SysUsers record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_users
     *
     * @param record the record
     * @return the int
     * @mbggenerated 
     */
    int updateByPrimaryKey(SysUsers record);
}
