/**
 * @author ldy
 */
package com.cmcc.ms.mapper;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.cmcc.ms.entity.usermanage.UsrManageBatchMessage;
import com.cmcc.ms.entity.usermanage.UsrManageBatchMessageExample;
import com.cmcc.ms.entity.usermanage.UsrManageBatchMessageWithBLOBs;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;


/**
 * The Interface UsrManageBatchMessageMapper.
 */
public interface UsrManageBatchMessageMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_manage_batch_message
     *
     * @param example the example
     * @return the int
     * @mbggenerated 
     */
    int countByExample(UsrManageBatchMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_manage_batch_message
     *
     * @param example the example
     * @return the int
     * @mbggenerated 
     */
    int deleteByExample(UsrManageBatchMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_manage_batch_message
     *
     * @param id the id
     * @return the int
     * @mbggenerated 
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_manage_batch_message
     *
     * @param record the record
     * @return the int
     * @mbggenerated 
     */
    int insert(UsrManageBatchMessageWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_manage_batch_message
     *
     * @param record the record
     * @return the int
     * @mbggenerated 
     */
    int insertSelective(UsrManageBatchMessageWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_manage_batch_message
     *
     * @param example the example
     * @return the list
     * @mbggenerated 
     */
    List<UsrManageBatchMessageWithBLOBs> selectByExampleWithBLOBs(UsrManageBatchMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_manage_batch_message
     *
     * @param example the example
     * @return the list
     * @mbggenerated 
     */
    List<UsrManageBatchMessage> selectByExample(UsrManageBatchMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_manage_batch_message
     *
     * @param id the id
     * @return the usr manage batch message with BLO bs
     * @mbggenerated 
     */
    UsrManageBatchMessageWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_manage_batch_message
     *
     * @param record the record
     * @param example the example
     * @return the int
     * @mbggenerated 
     */
    int updateByExampleSelective(@Param("record") UsrManageBatchMessageWithBLOBs record,
                                 @Param("example") UsrManageBatchMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_manage_batch_message
     *
     * @param record the record
     * @param example the example
     * @return the int
     * @mbggenerated 
     */
    int updateByExampleWithBLOBs(@Param("record") UsrManageBatchMessageWithBLOBs record,
                                 @Param("example") UsrManageBatchMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_manage_batch_message
     *
     * @param record the record
     * @param example the example
     * @return the int
     * @mbggenerated 
     */
    int updateByExample(@Param("record") UsrManageBatchMessage record,
                        @Param("example") UsrManageBatchMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_manage_batch_message
     *
     * @param record the record
     * @return the int
     * @mbggenerated 
     */
    int updateByPrimaryKeySelective(UsrManageBatchMessageWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_manage_batch_message
     *
     * @param record the record
     * @return the int
     * @mbggenerated 
     */
    int updateByPrimaryKeyWithBLOBs(UsrManageBatchMessageWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_manage_batch_message
     *
     * @param record the record
     * @return the int
     * @mbggenerated 
     */
    int updateByPrimaryKey(UsrManageBatchMessage record);

    /**
     * Gets the list for show.
     *
     * @param pb the pb
     * @return the list for show
     */
    //查找 用于列表展示
    List<UsrManageBatchMessageWithBLOBs> getListForShow(PageBounds pb);

    /**
     * Gets the usr manage batch msg by id.
     *
     * @param hm the hm
     * @return the usr manage batch msg by id
     */
    //查找  
    UsrManageBatchMessageWithBLOBs getUsrManageBatchMsgById(HashMap<String, Object> hm);

    /**
     * Update usr manage batch msg by id.
     *
     * @param hm the hm
     * @return the int
     */
    //删除短信(实际为更新)
    int updateUsrManageBatchMsgById(HashMap<String, Object> hm);

}
