apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2017-10-09T02:45:32Z
  labels:
    kubernetes-admin.caicloud.io/application: cdnms-jacoco
    kubernetes-admin.caicloud.io/type: application
  name: cdnms-jacoco
  namespace: demo
  resourceVersion: "47066670"
  selfLink: /api/v1/namespaces/demo/services/cdnms-jacoco
  uid: eb364c66-ac9b-11e7-943f-288023b66538
spec:
  clusterIP: 10.254.25.34
  ports:
  - name: a333
    nodePort: 32237
    port: 31313
    protocol: TCP
    targetPort: 8080
  - name: b444
    nodePort: 30904
    port: 31314
    protocol: TCP
    targetPort: 8494
  selector:
    kubernetes-admin.caicloud.io/select-by: service_demo_cndmsjacoco
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
