/**
 * @author ldy
 */
package com.cmcc.ms.entity.system;

import java.util.Date;

import com.cmcc.ms.common.utils.StringUtil;
import com.cmcc.ms.common.utils.TimeUtils;


/**
 * The Class OperateLog.
 *
 * @author ldy
 */
public class OperateLog {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column operate_log.ID
     * 
     * @mbggenerated
     */
    private Integer id;

    /** The type. */
    private String type;

    /** The source. */
    private String source;

    /** The result. */
    private String result;

    /** The send msg. */
    private String sendMsg;

    /** The receive msg. */
    private String receiveMsg;

    /**
     * Gets the send msg.
     *
     * @return the send msg
     */
    public String getSendMsg() {
        return sendMsg;
    }

    /**
     * Sets the send msg.
     *
     * @param sendMsg the new send msg
     */
    public void setSendMsg(String sendMsg) {
        this.sendMsg = sendMsg;
    }

    /**
     * Gets the receive msg.
     *
     * @return the receive msg
     */
    public String getReceiveMsg() {
        return receiveMsg;
    }

    /**
     * Sets the receive msg.
     *
     * @param receiveMsg the new receive msg
     */
    public void setReceiveMsg(String receiveMsg) {
        this.receiveMsg = receiveMsg;
    }

    /**
     * Gets the type.
     *
     * @return the type
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the type.
     *
     * @param type the new type
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Gets the source.
     *
     * @return the source
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the source.
     *
     * @param source the new source
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * Gets the result.
     *
     * @return the result
     */
    public String getResult() {
        return result;
    }

    /**
     * Sets the result.
     *
     * @param result the new result
     */
    public void setResult(String result) {
        this.result = result;
    }

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column operate_log.USER_ID
     * 
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column operate_log.USER_NAME
     * 
     * @mbggenerated
     */
    private String userName;

    /** The user name show. */
    @SuppressWarnings("unused")
    private String userNameShow;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column operate_log.IP_ADDR
     * 
     * @mbggenerated
     */
    private String ipAddr;

    /** The ip addr show. */
    @SuppressWarnings("unused")
    private String ipAddrShow;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column operate_log.BROWSER
     * 
     * @mbggenerated
     */
    private String browser;

    /** The browser show. */
    @SuppressWarnings("unused")
    private String browserShow;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column operate_log.OPERATE_TIME
     * 
     * @mbggenerated
     */
    private Date operateTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column operate_log.OPERATE_CONTENT
     * 
     * @mbggenerated
     */
    @SuppressWarnings("unused")
    private String operateTimeShow;

    /**
     * Gets the operate time show.
     *
     * @return the operate time show
     */
    public String getOperateTimeShow() {
        String stringFromTime = "";
        if (operateTime != null) {
            stringFromTime = TimeUtils.getStringFromTime(operateTime, TimeUtils.FORMAT_DATE);
        }
        return stringFromTime;
    }

    /** The operate content. */
    private String operateContent;

    /** The operate content show. */
    @SuppressWarnings("unused")
    private String operateContentShow;

    /**
     * Gets the user name show.
     *
     * @return the user name show
     */
    public String getUserNameShow() {
        return StringUtil.xssCodeShow(userName);
    }

    /**
     * Gets the ip addr show.
     *
     * @return the ip addr show
     */
    public String getIpAddrShow() {
        return StringUtil.xssCodeShow(ipAddr);
    }

    /**
     * Gets the browser show.
     *
     * @return the browser show
     */
    public String getBrowserShow() {
        return StringUtil.xssCodeShow(browser);
    }

    /**
     * Gets the operate content show.
     *
     * @return the operate content show
     */
    public String getOperateContentShow() {
        return StringUtil.xssCodeShow(operateContent);
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column operate_log.ID
     * 
     * @return the value of operate_log.ID
     * 
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column operate_log.ID
     * 
     * @param id
     *            the value for operate_log.ID
     * 
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column operate_log.USER_ID
     * 
     * @return the value of operate_log.USER_ID
     * 
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column operate_log.USER_ID
     * 
     * @param userId
     *            the value for operate_log.USER_ID
     * 
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column operate_log.USER_NAME
     * 
     * @return the value of operate_log.USER_NAME
     * 
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column operate_log.USER_NAME
     * 
     * @param userName
     *            the value for operate_log.USER_NAME
     * 
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column operate_log.IP_ADDR
     * 
     * @return the value of operate_log.IP_ADDR
     * 
     * @mbggenerated
     */
    public String getIpAddr() {
        return ipAddr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column operate_log.IP_ADDR
     * 
     * @param ipAddr
     *            the value for operate_log.IP_ADDR
     * 
     * @mbggenerated
     */
    public void setIpAddr(String ipAddr) {
        this.ipAddr = ipAddr == null ? null : ipAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column operate_log.BROWSER
     * 
     * @return the value of operate_log.BROWSER
     * 
     * @mbggenerated
     */
    public String getBrowser() {
        return browser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column operate_log.BROWSER
     * 
     * @param browser
     *            the value for operate_log.BROWSER
     * 
     * @mbggenerated
     */
    public void setBrowser(String browser) {
        this.browser = browser == null ? null : browser.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column operate_log.OPERATE_TIME
     * 
     * @return the value of operate_log.OPERATE_TIME
     * 
     * @mbggenerated
     */
    public Date getOperateTime() {

        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column operate_log.OPERATE_TIME
     * 
     * @param operateTime
     *            the value for operate_log.OPERATE_TIME
     * 
     * @mbggenerated
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column operate_log.OPERATE_CONTENT
     * 
     * @return the value of operate_log.OPERATE_CONTENT
     * 
     * @mbggenerated
     */
    public String getOperateContent() {
        return operateContent;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column operate_log.OPERATE_CONTENT
     * 
     * @param operateContent
     *            the value for operate_log.OPERATE_CONTENT
     * 
     * @mbggenerated
     */
    public void setOperateContent(String operateContent) {
        this.operateContent = operateContent == null ? null : operateContent.trim();
    }
}
