package com.cmcc.ms.entity.system;



/**
 * The Class RoleMenuRelation.
 *
 * @author ldy
 */
public class RoleMenuRelation {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column role_menu_relation.ROLE_ID
     * 
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column role_menu_relation.MENU_ID
     * 
     * @mbggenerated
     */
    private Integer menuId;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column role_menu_relation.ROLE_ID
     * 
     * @return the value of role_menu_relation.ROLE_ID
     * 
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column role_menu_relation.ROLE_ID
     * 
     * @param roleId
     *            the value for role_menu_relation.ROLE_ID
     * 
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column role_menu_relation.MENU_ID
     * 
     * @return the value of role_menu_relation.MENU_ID
     * 
     * @mbggenerated
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column role_menu_relation.MENU_ID
     * 
     * @param menuId
     *            the value for role_menu_relation.MENU_ID
     * 
     * @mbggenerated
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }
}
