package com.cmcc.ms.entity.system;

import net.sf.json.JSONArray;


/**
 * 菜单实体.
 *
 * @author ldy
 */
public class SysMenus implements java.io.Serializable, Comparable<Object> {

    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = 1L;

    /** The checked. */
    private boolean checked;

    /**
     * Gets the checked.
     *
     * @return the checked
     */
    public boolean getChecked() {
        return checked;
    }

    /**
     * Sets the checked.
     *
     * @param checked the new checked
     */
    public void setChecked(boolean checked) {
        this.checked = checked;
    }

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column sys_menus.MENU_ID
     * 
     * @mbggenerated
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column sys_menus.MENU_NAME
     * 
     * @mbggenerated
     */
    private String menuName;

    /** The title. */
    private String title;

    /**
     * Gets the title.
     *
     * @return the title
     */
    public String getTitle() {
        this.title = this.menuName;
        return title;
    }

    /**
     * Sets the title.
     */
    public void setTitle() {
        this.title = this.menuName;
    }

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column sys_menus.PARENT_ID
     * 
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column sys_menus.DEPTH
     * 
     * @mbggenerated
     */
    private Integer depth;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column sys_menus.URL
     * 
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column sys_menus.TYPE
     * 
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column sys_menus.IMG
     * 
     * @mbggenerated
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column sys_menus.SORT
     * 
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column sys_menus.MENU_ID
     * 
     * @return the value of sys_menus.MENU_ID
     * 
     * @mbggenerated
     */

    private JSONArray children = new JSONArray();

    /**
     * Gets the children.
     *
     * @return the children
     */
    public JSONArray getChildren() {
        return children;
    }

    /**
     * Sets the children.
     *
     * @param children the new children
     */
    public void setChildren(JSONArray children) {
        this.children = children;
    }

    /**
     * Gets the menu id.
     *
     * @return the menu id
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sys_menus.MENU_ID
     * 
     * @param menuId
     *            the value for sys_menus.MENU_ID
     * 
     * @mbggenerated
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column sys_menus.MENU_NAME
     * 
     * @return the value of sys_menus.MENU_NAME
     * 
     * @mbggenerated
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sys_menus.MENU_NAME
     * 
     * @param menuName
     *            the value for sys_menus.MENU_NAME
     * 
     * @mbggenerated
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column sys_menus.PARENT_ID
     * 
     * @return the value of sys_menus.PARENT_ID
     * 
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sys_menus.PARENT_ID
     * 
     * @param parentId
     *            the value for sys_menus.PARENT_ID
     * 
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column sys_menus.DEPTH
     * 
     * @return the value of sys_menus.DEPTH
     * 
     * @mbggenerated
     */
    public Integer getDepth() {
        return depth;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sys_menus.DEPTH
     * 
     * @param depth
     *            the value for sys_menus.DEPTH
     * 
     * @mbggenerated
     */
    public void setDepth(Integer depth) {
        this.depth = depth;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column sys_menus.URL
     * 
     * @return the value of sys_menus.URL
     * 
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sys_menus.URL
     * 
     * @param url
     *            the value for sys_menus.URL
     * 
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column sys_menus.TYPE
     * 
     * @return the value of sys_menus.TYPE
     * 
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sys_menus.TYPE
     * 
     * @param type
     *            the value for sys_menus.TYPE
     * 
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column sys_menus.IMG
     * 
     * @return the value of sys_menus.IMG
     * 
     * @mbggenerated
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sys_menus.IMG
     * 
     * @param img
     *            the value for sys_menus.IMG
     * 
     * @mbggenerated
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column sys_menus.SORT
     * 
     * @return the value of sys_menus.SORT
     * 
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sys_menus.SORT
     * 
     * @param sort
     *            the value for sys_menus.SORT
     * 
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /** 
     * (non-Javadoc)
     * @see java.lang.Comparable#compareTo(java.lang.Object)
     */
    public int compareTo(Object o) {
        SysMenus sysMenus = (SysMenus) o;
        if (this.menuId.intValue() > sysMenus.menuId.intValue()) {
            return 1;
        }
        if (this.menuId.intValue() < sysMenus.menuId.intValue()) {
            return -1;
        }
        return 0;
    }

    /**
     *  (non-Javadoc)
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
        return super.equals(obj);
    }

    /**
     *  (non-Javadoc)
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        return super.hashCode();
    }

}
