package com.cmcc.ms.entity.system;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.cmcc.ms.common.utils.TimeUtils;



/**
 * The Class SysRolesManual.
 *
 * @author ldy
 */
public class SysRolesManual {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column sys_roles.ROLE_ID
     * 
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column sys_roles.ROLE_NAME
     * 
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column sys_roles.ROLE_DESC
     * 
     * @mbggenerated
     */
    private String roleDesc;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column sys_roles.COMPANY
     * 
     * @mbggenerated
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column sys_roles.CREATE_DATE
     * 
     * @mbggenerated
     */
    private Date createDate;

    /** The create time. */
    private String createTime;

    /**
     * Gets the creates the time.
     *
     * @return the creates the time
     */
    public String getCreateTime() {
        if (createDate != null) {
            createTime = TimeUtils
                    .getStringFromTime(createDate, TimeUtils.FORMAT_DATE_TIME_SECONDS);
        }
        return createTime;
    }

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column sys_roles.LASTWROTIME
     * 
     * @mbggenerated
     */
    private Date lastwrotime;

    /** The last time. */
    private String lastTime;

    /**
     * Gets the last time.
     *
     * @return the last time
     */
    public String getLastTime() {
        if (lastwrotime != null) {
            lastTime = TimeUtils.getStringFromTime(lastwrotime, TimeUtils.FORMAT_DATE_TIME_SECONDS);
        }
        return lastTime;
    }

    /** The users count. */
    private int usersCount;

    /**
     * Gets the users count.
     *
     * @return the users count
     */
    public int getUsersCount() {
        return usersCount;
    }

    /**
     * Sets the users count.
     *
     * @param usersCount the new users count
     */
    public void setUsersCount(int usersCount) {
        this.usersCount = usersCount;
    }

    /** The sys menus. */
    // -------------------------------//
    private List<SysMenus> sysMenus;

    /**
     * Gets the sys menus.
     *
     * @return the sys menus
     */
    public List<SysMenus> getSysMenus() {
        return sysMenus != null ? sysMenus : new ArrayList<SysMenus>();
    }

    /**
     * Sets the sys menus.
     *
     * @param sysMenus the new sys menus
     */
    public void setSysMenus(List<SysMenus> sysMenus) {
        this.sysMenus = sysMenus;
    }

    // -------------------------------//

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column sys_roles.ROLE_ID
     * 
     * @return the value of sys_roles.ROLE_ID
     * 
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sys_roles.ROLE_ID
     * 
     * @param roleId
     *            the value for sys_roles.ROLE_ID
     * 
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column sys_roles.ROLE_NAME
     * 
     * @return the value of sys_roles.ROLE_NAME
     * 
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sys_roles.ROLE_NAME
     * 
     * @param roleName
     *            the value for sys_roles.ROLE_NAME
     * 
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column sys_roles.ROLE_DESC
     * 
     * @return the value of sys_roles.ROLE_DESC
     * 
     * @mbggenerated
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sys_roles.ROLE_DESC
     * 
     * @param roleDesc
     *            the value for sys_roles.ROLE_DESC
     * 
     * @mbggenerated
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc == null ? null : roleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column sys_roles.COMPANY
     * 
     * @return the value of sys_roles.COMPANY
     * 
     * @mbggenerated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sys_roles.COMPANY
     * 
     * @param company
     *            the value for sys_roles.COMPANY
     * 
     * @mbggenerated
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column sys_roles.CREATE_DATE
     * 
     * @return the value of sys_roles.CREATE_DATE
     * 
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate != null ? createDate : new Date();
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sys_roles.CREATE_DATE
     * 
     * @param createDate
     *            the value for sys_roles.CREATE_DATE
     * 
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column sys_roles.LASTWROTIME
     * 
     * @return the value of sys_roles.LASTWROTIME
     * 
     * @mbggenerated
     */
    public Date getLastwrotime() {
        return lastwrotime != null ? lastwrotime : new Date();
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sys_roles.LASTWROTIME
     * 
     * @param lastwrotime
     *            the value for sys_roles.LASTWROTIME
     * 
     * @mbggenerated
     */
    public void setLastwrotime(Date lastwrotime) {
        this.lastwrotime = lastwrotime;
    }
}
